"""add edit_view_s3_key field to transaction model

Revision ID: 2b5d6da10818
Revises: ec6b4340d9c1
Create Date: 2025-01-26 10:08:30.419038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5d6da10818'
down_revision: Union[str, None] = 'ec6b4340d9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_transactions', sa.Column('edit_view_s3_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_transactions', 'edit_view_s3_key')
    # ### end Alembic commands ###
