"""add user_id field to DbPurchase model

Revision ID: 3315a039650f
Revises: 4e9218d775c1
Create Date: 2024-02-25 12:42:51.358484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3315a039650f'
down_revision: Union[str, None] = '4e9218d775c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_purchases', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_purchases', 'user_id')
    # ### end Alembic commands ###
