"""add thumbnail_s3_key to transaction model

Revision ID: 4226e49c7816
Revises: f0be564f2c10
Create Date: 2025-01-04 18:09:12.863494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4226e49c7816'
down_revision: Union[str, None] = 'f0be564f2c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_transactions', sa.Column('thumbnail_s3_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_transactions', 'thumbnail_s3_key')
    # ### end Alembic commands ###
