"""add digital_balance and cash_balance fields directly to user model

don't need to make a wallet table yet

Revision ID: 681c905a60ca
Revises: 84319f6b30b7
Create Date: 2024-07-01 15:49:47.799122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '681c905a60ca'
down_revision: Union[str, None] = '84319f6b30b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_users', sa.Column('digital_balance', sa.Float(), nullable=True))
    op.add_column('expense_users', sa.Column('cash_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_users', 'cash_balance')
    op.drop_column('expense_users', 'digital_balance')
    # ### end Alembic commands ###
