"""add note field to transactions for explanations

Revision ID: 75420f2022a4
Revises: dfdbbbc3e8d2
Create Date: 2024-07-04 11:26:37.895974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75420f2022a4'
down_revision: Union[str, None] = 'dfdbbbc3e8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_transactions', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_transactions', 'note')
    # ### end Alembic commands ###
