"""rename type to payment_method for tracking cash/card transactions

Revision ID: 84319f6b30b7
Revises: c4f02f4aaf72
Create Date: 2024-06-23 13:47:38.054828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84319f6b30b7'
down_revision: Union[str, None] = 'c4f02f4aaf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_transactions', sa.Column('payment_method', sa.Enum('CASH', 'CARD', name='paymentmethod'), nullable=True))

    # Transfer data from type to payment_method
    connection = op.get_bind()
    connection.execute(
        text("""
        UPDATE expense_transactions
        SET payment_method = type
        """)
    )

    op.drop_index('ix_expense_purchases_id', table_name='expense_transactions')
    op.create_index(op.f('ix_expense_transactions_id'), 'expense_transactions', ['id'], unique=False)
    op.drop_column('expense_transactions', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_transactions', sa.Column('type', mysql.ENUM('CASH', 'CARD'), nullable=True))

    # Transfer data back from payment_method to type
    connection = op.get_bind()
    connection.execute(
        text("""
        UPDATE expense_transactions
        SET type = payment_method
        """)
    )

    op.drop_index(op.f('ix_expense_transactions_id'), table_name='expense_transactions')
    op.create_index('ix_expense_purchases_id', 'expense_transactions', ['id'], unique=False)
    op.drop_column('expense_transactions', 'payment_method')
    # ### end Alembic commands ###
