"""add feature_camera to user model

Revision ID: bccf07568e93
Revises: 75420f2022a4
Create Date: 2024-12-31 14:24:26.626391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bccf07568e93'
down_revision: Union[str, None] = '75420f2022a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_users', sa.Column('feature_camera', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_users', 'feature_camera')
    # ### end Alembic commands ###
