"""add transaction type to transaction model

to allow for top ups and cash withdrawals along with card/cash purchases

Revision ID: dfdbbbc3e8d2
Revises: 7e85b9e2594c
Create Date: 2024-07-02 14:16:21.469271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfdbbbc3e8d2'
down_revision: Union[str, None] = '7e85b9e2594c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_transactions', sa.Column('transaction_type', sa.Enum('PURCHASE', 'TOPUP', 'WITHDRAW', name='transactiontype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_transactions', 'transaction_type')
    # ### end Alembic commands ###
