"""add receipt lottery number field to transaction model

Revision ID: ec6b4340d9c1
Revises: 4226e49c7816
Create Date: 2025-01-07 15:08:51.817109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6b4340d9c1'
down_revision: Union[str, None] = '4226e49c7816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_transactions', sa.Column('receipt_lottery_number', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_transactions', 'receipt_lottery_number')
    # ### end Alembic commands ###
