"""add s3_key field to transaction model

Revision ID: f0be564f2c10
Revises: bccf07568e93
Create Date: 2025-01-03 16:51:02.782926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0be564f2c10'
down_revision: Union[str, None] = 'bccf07568e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense_transactions', sa.Column('s3_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense_transactions', 's3_key')
    # ### end Alembic commands ###
